<p style="font-family: Arial; font-size:3em;color:black;"> Lab 1(Arrays) </p>

# Installation and imports

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
# Create a numpy array with the elements "1, 2, 3, 5, 0", print the array and test if all of its elements are non-zero.
arr_1 = np.array([1,2,3,5,0])
print("numpy array: ", arr_1)

all_no_zero = np.all(arr_1 != 0)
print("All elements are non-zero: ", all_no_zero)


numpy array:  [1 2 3 5 0]
All elements are non-zero:  False


In [ ]:
# Create a numpy array with the elements "3, -1, 3, 7, 2", print the array and test if any of its elements is non-zero.
arr_2 = np.array([3,-1,3,7,2])
print("numpy array: ", arr_2)

all_no_zero = np.all(arr_2 != 0)
print("All elements are non-zero: ", all_no_zero)

numpy array:  [ 3 -1  3  7  2]
All elements are non-zero:  True


In [ ]:
# Create a numpy array with the elements "0, 0, 0, 0", print the array and test if any of its elements is non-zero.
arr_3 = np.array([0,0,0,0,0])
print("numpy array: ", arr_3)

all_no_zero = np.all(arr_3 != 0)
print("All elements are non-zero: ", all_no_zero)

numpy array:  [0 0 0 0 0]
All elements are non-zero:  False


In [ ]:
# Create a numpy array with the elements "56, -2, 7", print the array and the amount of memory required to store it.
arr_4 = np.array([56, -2, 7])
print("numpy array: ",arr_4)
memory_require = arr_4.nbytes
print("Amount of memory required to store it in bytes: ", memory_require)

numpy array:  [56 -2  7]
Amount of memory required to store it in bytes:  12


In [ ]:
# Create a numpy array with 10 zeros and print the array.
arr_5 = np.array(10*[0])
print(arr_5)
# Create a numpy array with 6 ones and print the array.
arr_6 = np.array(6*[1])
print(arr_6)
# Create a numpy array with 12 '3's and print the array. [3 3 3 3 3 3 3 3 3 3 3 3]
arr_7 = np.array(12*[3])
print(arr_7)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1]
[3 3 3 3 3 3 3 3 3 3 3 3]


In [ ]:
# Create a numpy array of the integers from 8 to 20 and print the array. (make sure 20 itself is included) hint:  use "arange" method
arr_8 = np.arange(8,21,1)
print(arr_8)
# Create a numpy array of the even integers from 8 to 20 and print the array. (make sure 20 itself is included)   hint:  use "arange" method
arr_9 = np.arange(8,21,2)
print(arr_9)

[ 8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 8 10 12 14 16 18 20]


In [ ]:
# Create a numpy array consisting of 100 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
mean_value_10 = 2
std_deviation_10 = 0.5
arr_10 = np.random.normal(mean_value_10, std_deviation_10, 100)
mean_value = np.mean(arr_10)
max_value_10 = np.max(arr_10)
min_value_10 = np.min(arr_10)
std_deviation = np.mean(arr_10)
print("Mean of 100: ", mean_value)
print("Max of 100: ", max_value_10)
print("Min of 100; ", min_value_10)
print("Standard Deviation of 100: ", std_deviation_10)
# Create a numpy array consisting of 1000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
mean_value_10 = 2
std_deviation_10 = 0.5
arr_10 = np.random.normal(mean_value_10, std_deviation_10, 1000)
mean_value = np.mean(arr_10)
max_value_10 = np.max(arr_10)
min_value_10 = np.min(arr_10)
std_deviation = np.mean(arr_10)
print("Mean of 1000: ", mean_value)
print("Max of 1000: ", max_value_10)
print("Min of 1000; ", min_value_10)
print("Standard Deviation of 1000: ", std_deviation_10)
# Create a numpy array consisting of 1000000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
mean_value_10 = 2
std_deviation_10 = 0.5
arr_10 = np.random.normal(mean_value_10, std_deviation_10, 1000000)
mean_value = np.mean(arr_10)
max_value_10 = np.max(arr_10)
min_value_10 = np.min(arr_10)
std_deviation = np.mean(arr_10)
print("Mean of 1000000: ", mean_value)
print("Max of 1000000: ", max_value_10)
print("Min of 1000000: ", min_value_10)
print("Standard Deviation of 1000000: ", std_deviation_10)
# (Bonus question) Looking at the three above examples with 1000, 5000, and 10000 random elements, do you have any observations about mean and std values?
print("1000 elements:")
mean_value_10 = 2
std_deviation_10 = 0.5
arr_10 = np.random.normal(mean_value_10, std_deviation_10, 1000)
mean_value = np.mean(arr_10)
max_value_10 = np.max(arr_10)
min_value_10 = np.min(arr_10)
std_deviation = np.mean(arr_10)
print("Mean of 1000: ", mean_value)
print("Max of 1000: ", max_value_10)
print("Min of 1000: ", min_value_10)
print("Standard Deviation of 1000: ", std_deviation_10)

print("5000 elements:")
mean_value_10 = 2
std_deviation_10 = 0.5
arr_10 = np.random.normal(mean_value_10, std_deviation_10, 5000)
mean_value = np.mean(arr_10)
max_value_10 = np.max(arr_10)
min_value_10 = np.min(arr_10)
std_deviation = np.mean(arr_10)
print("Mean of 5000: ", mean_value)
print("Max of 5000: ", max_value_10)
print("Min of 5000: ", min_value_10)
print("Standard Deviation of 5000: ", std_deviation_10)

print("10000 elements:")
mean_value_10 = 2
std_deviation_10 = 0.5
arr_10 = np.random.normal(mean_value_10, std_deviation_10, 10000)
mean_value = np.mean(arr_10)
max_value_10 = np.max(arr_10)
min_value_10 = np.min(arr_10)
std_deviation = np.mean(arr_10)
print("Mean of 10000: ", mean_value)
print("Max of 10000: ", max_value_10)
print("Min of 10000: ", min_value_10)
print("Standard Deviation of 10000: ", std_deviation_10)

Mean of 100:  1.9262548110850282
Max of 100:  3.138827506916621
Min of 100;  0.7553979844694312
Standard Deviation of 100:  0.5
Mean of 1000:  1.9934429768323263
Max of 1000:  3.4511988311462725
Min of 1000;  0.3974926781567967
Standard Deviation of 1000:  0.5
Mean of 1000000:  1.9994280240151527
Max of 1000000:  4.511925121041065
Min of 1000000:  -0.570071249784522
Standard Deviation of 1000000:  0.5
1000 elements:
Mean of 1000:  2.005881217240898
Max of 1000:  3.5165561391585958
Min of 1000:  0.3752971974831878
Standard Deviation of 1000:  0.5
5000 elements:
Mean of 5000:  2.0010829292691312
Max of 5000:  4.1608242430906754
Min of 5000:  0.0979348974054739
Standard Deviation of 5000:  0.5
10000 elements:
Mean of 10000:  2.005365965589817
Max of 10000:  3.7413660538095224
Min of 10000:  0.018026552883578573
Standard Deviation of 10000:  0.5
CONCLUSION
Look at the examples above, I observed that whenever increasing the random elements, there will be a little change of mean, which can b

# CONCLUSION

Look at the examples above, I observed that whenever increasing the random elements, there will be a little change of mean, which can be seen as approximately equal to 2. Indeed, the Standard Deviation does not change in every case