<p style="font-family: Arial; font-size:3em;color:black;"> Matrices(Lab 3) </p>

In [1]:
!pip install numpy

In [ ]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import det

In [ ]:
import numpy as np

# 1) Defining matrix A
A = np.array([[5, 2, 3],
              [6, 1, 3],
              [2, 4, 1]])

# Defining matrix B using slicing to get the top left 2x2 part of A
B = A[:2, :2]

# Defining matrix C using slicing to get the bottom right 2x2 part of A
C = A[1:, 1:]

In [ ]:
A, B, C

(array([[5, 2, 3],
        [6, 1, 3],
        [2, 4, 1]]),
 array([[5, 2],
        [6, 1]]),
 array([[1, 3],
        [4, 1]]))

In [ ]:
# 2) Defining matrix D
D = np.array([[4, -7, 4],
              [5, 6, -1],
              [-4, 2, 5]])
print(D)

[[ 4 -7  4]
 [ 5  6 -1]
 [-4  2  5]]


In [ ]:
# Calculating the matrix product AD
AD = np.matmul(A, D)
print("AD is:", AD)

# Calculate the matrix product DA
DA = np.matmul(D, A)
print("DA is:", DA)

# Check if AD and DA are equal
are_equal = np.array_equal(AD, DA)

# Show an answer if they are equal or not
equality_statement = "AD and DA are equal." if are_equal else "AD and DA are not equal."

print(equality_statement)

AD is: [[ 18 -17  33]
 [ 17 -30  38]
 [ 24  12   9]]
DA is: [[-14  17  -5]
 [ 59  12  32]
 [  2  14  -1]]
AD and DA are not equal.


## **Manually calculating the determinant of B:**

$\text{det}(B) = 5 \cdot 1 - 2 \cdot 6 = 5 - 12 = -7$


# **Manually Calculating the inverse of B:**

$B^{-1}$ = $\frac{1}{-7}$ \begin{bmatrix} 1 & -2 \\ -6 & 5 \end{bmatrix}
      = \begin{bmatrix} -1/7 & 2/7 \\ 6/7 & -5/7 \end{bmatrix}
      = \begin{bmatrix} -0.14285714 & 0.28571429 \\ 0.85714286 & -0.71428571 \end{bmatrix}

In [ ]:
# Using numpy to calculate the determinant of B
det_B = np.linalg.det(B)

# Using numpy to calculate the inverse of B
inv_B = np.linalg.inv(B)

print(det_B, inv_B)

-6.999999999999999 [[-0.14285714  0.28571429]
 [ 0.85714286 -0.71428571]]


In [ ]:
# Using numpy to calculate the inverse of D
inv_D = np.linalg.inv(D)

# Calculating D times the inverse of D
D_invD = np.matmul(D, inv_D)

# Calculating the inverse of D times D
invD_D = np.matmul(inv_D, D)

#Showing the results
print("D * D^-1:", D_invD)
print("D^-1 * D:", invD_D)

# Checking if both products are identity matrices
is_D_invD_identity = np.allclose(D_invD, np.eye(3))
is_invD_D_identity = np.allclose(invD_D, np.eye(3))

confirmation_message = "Both D * D^-1 and D^-1 * D are identity matrices." if is_D_invD_identity and is_invD_D_identity else "One of the products is not an identity matrix."

print(confirmation_message)

D * D^-1: [[ 1.00000000e+00  1.11022302e-16  0.00000000e+00]
 [ 6.93889390e-17  1.00000000e+00 -5.55111512e-17]
 [-1.38777878e-17 -8.32667268e-17  1.00000000e+00]]
D^-1 * D: [[ 1.00000000e+00  6.93889390e-17  6.93889390e-18]
 [ 2.77555756e-17  1.00000000e+00 -2.08166817e-17]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Both D * D^-1 and D^-1 * D are identity matrices.


# The observation here is that when a matrix is multiplied by its inverse, the result is an identity matrix.
