<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 8</p>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.metrics import classification_report

In [ ]:
# Import the built-in iris dataset to work with
iris = datasets.load_iris() # the dataset consists of 3 different types of irises' (Setosa, Versicolour, and Virginica) petal and sepal length
print("iris dataset",iris.data[:10,:])
X = iris.data[:, :2] # We only want to use the first two features (Sepal Length, Sepal Width)
y = iris.target # corresponding to 'setosa', 'versicolor', 'virginica
print("iris target",y[:10,])

iris dataset [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
iris target [0 0 0 0 0 0 0 0 0 0]


In [ ]:
# Develop a linear Support Vector Machine to classify the irises
# Use GridSearchCV to optimize the model's hyperparameters (C, gamma, kernel)
# Compare the accuracies of the above two models

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

linear_svm_model = SVC(kernel='linear')
linear_svm_model.fit(X_train,y_train)
y_pred_lin = linear_svm_model.predict(X_test)

linear_svm_accuaracy = accuracy_score(y_test, y_pred_lin)
lin_report = classification_report(y_test, y_pred_lin)

print('Linear SVM Accuracy: ', linear_svm_accuaracy)
print('Classification Report: \n', lin_report)

Linear SVM Accuracy:  0.8
Classification Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.70      0.54      0.61        13
           2       0.62      0.77      0.69        13

    accuracy                           0.80        45
   macro avg       0.78      0.77      0.77        45
weighted avg       0.81      0.80      0.80        45



In [ ]:
param_grid = {
    'C': [0.1,1,10,100,1000],
    'kernel': ['poly','linear','rbf', 'sigmoid'],
    'gamma': ['auto','scale']
}

optimized_svm = SVC()
grid_search = GridSearchCV(estimator=optimized_svm, param_grid=param_grid, cv = 5, verbose=1)
grid_search.fit(X_train, y_train)

best_params = grid_search.best_params_
best_svm_model = grid_search.best_estimator_
y_pred = best_svm_model.predict(X_test)

best_svm_accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(report)

print(f'The Linear SVM model obtained an accuracy of: {linear_svm_accuaracy}\nThe Linear SVM model with hyperparameter tuning: {best_svm_accuracy}\nBest Hyperparameters: {best_params}')

Fitting 5 folds for each of 40 candidates, totalling 200 fits
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.73      0.62      0.67        13
           2       0.67      0.77      0.71        13

    accuracy                           0.82        45
   macro avg       0.80      0.79      0.79        45
weighted avg       0.82      0.82      0.82        45

The Linear SVM model obtained an accuracy of: 0.8
The Linear SVM model with hyperparameter tuning: 0.8222222222222222
Best Hyperparameters: {'C': 0.1, 'gamma': 'auto', 'kernel': 'rbf'}
