## <p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 4 </p>

# Installations and imports

## Installations

In [1]:
!pip install numpy

## Imports

# Task 1: Calculate the bag of words (without TF-IDF, just word counts) matrix for the following 5 phrases.
- college student
- airport taxi driver
- Toronto art museum
- life art
- machine learning student

In [2]:
import numpy as np

# Define the list of phrases
phrases = [
     "college student",
     "airport taxi driver",
     "Toronto art museum",
     "life art",
     "machine learning student"
]
print(f'phrases: {phrases}')

words = [phrase.split() for phrase in phrases]
print(f'words: {words}')

phrases: ['college student', 'airport taxi driver', 'Toronto art museum', 'life art', 'machine learning student']
words: [['college', 'student'], ['airport', 'taxi', 'driver'], ['Toronto', 'art', 'museum'], ['life', 'art'], ['machine', 'learning', 'student']]


In [3]:
raw_list = list(set([word for phrase in words for word in phrase]))
print(f'raw vocabulary {raw_list}')

raw vocabulary ['student', 'airport', 'taxi', 'museum', 'machine', 'driver', 'Toronto', 'art', 'learning', 'college', 'life']


In [4]:
vocabulary = sorted(raw_list)
print(f'vocabulary: {vocabulary}')

vocabulary: ['Toronto', 'airport', 'art', 'college', 'driver', 'learning', 'life', 'machine', 'museum', 'student', 'taxi']


In [5]:
total_phrases = len(phrases)
print(f'Total of phrases {total_phrases}')
total_words = len(vocabulary)
print(f'Total of Unique words {total_words}')
bag_of_words_matrix = np.zeros((total_phrases, total_words), dtype=int)
print('bag_of_words_matrix (init): ')
print(bag_of_words_matrix)

Total of phrases 5
Total of Unique words 11
bag_of_words_matrix (init): 
[[0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]]


In [6]:
enumerated_phrases = enumerate(phrases)
print(f'Enumerated phrases {enumerated_phrases}')

for i, phrase in enumerated_phrases:
    for word in phrase.split():
        word_index = vocabulary.index(word)
        bag_of_words_matrix[i, word_index] += 1

Enumerated phrases <enumerate object at 0x7909585989c0>


In [7]:
print('bag_of_words_matrix (final): ')
print(bag_of_words_matrix)

bag_of_words_matrix (final): 
[[0 0 0 1 0 0 0 0 0 1 0]
 [0 1 0 0 1 0 0 0 0 0 1]
 [1 0 1 0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 1 0]]


# Task 2: Calculate the IDF for the words “college” and “art”.

In [8]:
def calculate_idf(searched_word):
    count = 0
    for phrase in phrases:
        arr_phrase = phrase.split()
        for word in arr_phrase:
            if searched_word == word:
                count+= 1

    if count == 0:
        print(f'We didnt find the word "{searched_word}" in the phrases: {phrases}.')
        return

    total_phrases = len(phrases)
    pretty_division = total_phrases / count
    print(f'IDF of "{searched_word}": {np.log10(pretty_division)}')

In [9]:
calculate_idf('art')

IDF of "art": 0.3979400086720376


In [10]:
calculate_idf('college')

IDF of "college": 0.6989700043360189
